### ISSUE TITLE
Mobile Responsive - Content is squashed rather than stacked

### ISSUE THREAD

**Issue by markbiernat** [Enclavely/tailor#130]
Tailor is brilliant, yet can not make it mobile responsive in the traditional sense - It could be the way I am using it.

For example:
When two content areas are side by side they look good in a desktop view.
However, in a mobile view they squash rather than stack the content areas.
I understand I am constraining it in a box or card or grid. But there must be a way to represent them side by side in the desktop view and then stacking them in the mobile view.

Please see the images as illustration to give more clarify.

This is the desktop view:

![full](https://user-images.githubusercontent.com/30418497/28542578-a4cefc1a-708a-11e7-9396-a27db67a7bd3.jpg)

This is the tailor mobile view: (I understand I put them in a box)

![tailer mobile](https://user-images.githubusercontent.com/30418497/28542593-afed2eaa-708a-11e7-8d80-acab5833799f.jpg)

This is what I would like to see in a mobile view:  (If you check sites like Apple, this is what happens).

![mobile](https://user-images.githubusercontent.com/30418497/28542598-b9290f84-708a-11e7-9c93-03118f91b9ea.jpg)

Thank you.

**Comment by fatherb** [comment]
Not sure whether to open a new issue or not but can confirm this issue is still occurring in the latest Tailor 1.81. I have set new breakpoints of Mobile: 767 and Tablet: 979 in customiser.

![screenshot 2017-08-23 09 56 46](https://user-images.githubusercontent.com/4437677/29607523-67e0388e-87e9-11e7-9abe-057e8cd06d18.png)


Testing website with Tailor 1.8.1 and Wordpress 4.8.1 - testing site in new Tailor viewport view and on Sizzy.co shows that four columns still not stacking on iPhone 6 and 7, Galaxy S4+, Nexus 6+ etc.  It does stack on iphone 4 and 5. 

![screenshot 2017-08-23 09 53 51](https://user-images.githubusercontent.com/4437677/29607428-1484187c-87e9-11e7-93ef-08a43499a447.png)

**Comment by munirkamal** [comment]
Hi @fatherb,

Could you please try the tailor demo site to see if the columns are stacking fine on that? This demo site is also using the latest version of Tailor and also the same breakpoints as you mention.

http://tailordemo.sandboxwp.io/

![image](https://user-images.githubusercontent.com/5817882/29610832-df6dd4da-8814-11e7-8639-a0787fe03fe5.png)

Also, please make sure you in the row settings you have the minimum screen size set to Tablet and not mobile. 
![image](https://user-images.githubusercontent.com/5817882/29611006-6a1ef3d4-8815-11e7-842d-6a8067ce682b.png)

**Comment by fatherb** [comment]
Hi - just checked the demo site. It is working correctly, but it doesn't have a grid of 4 columns anywhere to match my site.

Here's my setting for that grid.

![screenshot 2017-08-23 15 13 16](https://user-images.githubusercontent.com/4437677/29620596-452ee15a-8816-11e7-8ae8-74dfe675d45c.png)

Think something else is going wrong. I've checked my additional css but nothing interferes with grid. This looks to be the code that creates the grid - it appears in _grid.scss and looks like it completely ignores the mobile breakpoint overrides put in place by Tailor -> Layout in customiser. It is still referring to 321px - the default breakpoint before you change it.

`@media only screen and (min-width: 321px)
_grid.scss:55
.tailor-ui .tailor-grid--tablet.tailor-grid--4>.tailor-grid__item {
    width: 25%;
}`

Could this be an issue with write permissions to a file in Tailor? Maybe those defaults aren't being processed by scss and updated into new css? 

Is there anywhere I can check to see if something is not being changed from the chosen breakpoints into code?

**Comment by munirkamal** [comment]
Hi,

I just tested it on the live demo. Added a for column "Grid Element" and tested the mobile view and it looks stacking fine there.

Gif preview:
http://www.giphy.com/gifs/l3c5GoATujGqD7LCo

You may also do a live test here:
https://sandboxwp.io/create/tailor

I guess you might be having some cache issue? Does the front end CSS file loading from the upload folder? uploads/tailor/css/frontend.min.css?ver=1.8.1

**Comment by fatherb** [comment]
Thanks for trying to help.

Maybe it is a cache issue - but this has been all day now, so surely the items would have refreshed by now.

Anyway, checked the source file for the front page. Tailor is loaded here:
`<link rel='stylesheet' id='tailor-styles-css'  href='http://www.connectscaffoldingservices.co.uk/wp-content/plugins/tailor/assets/css/frontend.min.css?ver=1.8.1' type='text/css' media='all' />`

and here: 
`<script type='text/javascript' src='http://www.connectscaffoldingservices.co.uk/wp-content/plugins/tailor/assets/js/dist/frontend.min.js?ver=1.8.1'></script>`

Plus there is some dynamic css being loaded which looks like the overrides from customiser:
`

<style id="tailor-dynamic-css" type="text/css">
--
  | .tailor-ui  .tailor-590b720b6ccbm{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}.tailor-ui  .tailor-590b720b6ccbm{border-style:none;}.tailor-ui .tailor-590b720b6ccbl.tailor-grid.tailor-grid--bordered .tailor-grid__item{border-style:none!important;}.tailor-ui .tailor-590b720b6ccca a{color:#444444;}.tailor-ui .tailor-590b720b6cccb a{color:#444444;}.tailor-ui .tailor-590b720b6cccc a{color:#444444;}.tailor-ui .tailor-590b720b6cccd a{color:#444444;}.tailor-ui .tailor-590b720b6ccbn .tailor-section__content{max-width:1200px;}.tailor-ui  .tailor-590b720b6ccbf{background-color:rgba(0,0,0,0.16);}.tailor-ui  .tailor-590b720b6ccbh{background-color:#000000;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner{color:#ffffff;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner{background-color:#000000;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner{border-style:none;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner:hover,.tailor-ui .tailor-590b720b6cccg .tailor-button__inner:focus{color:#f2f2f2;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner:hover,.tailor-ui .tailor-590b720b6cccg .tailor-button__inner:focus{background-color:#000000;}.tailor-ui .tailor-590b720b6cccg .tailor-button__inner:active{background-color:#000000;}@media only screen and (min-width:980px){.tailor-ui  .tailor-590b720b6ccbo{width:33.3%;}.tailor-ui  .tailor-590b720b6ccbs{width:33.3%;}.tailor-ui  .tailor-590b720b6ccbu{width:33.3%;}}@media only screen and (min-width:768px) and (max-width:979px){.tailor-ui .mobile-columns .tailor-590b720b6ccbo,.tailor-ui .tablet-columns .tailor-590b720b6ccbo{width:33.3%;}.tailor-ui .mobile-columns .tailor-590b720b6ccbs,.tailor-ui .tablet-columns .tailor-590b720b6ccbs{width:33.3%;}.tailor-ui .mobile-columns .tailor-590b720b6ccbu,.tailor-ui .tablet-columns .tailor-590b720b6ccbu{width:33.3%;}}@media only screen and (max-width:767px){.tailor-ui .mobile-columns .tailor-590b720b6ccbo{width:33.3%;}.tailor-ui .mobile-columns .tailor-590b720b6ccbs{width:33.3%;}.tailor-ui .mobile-columns .tailor-590b720b6ccbu{width:33.3%;}}
  | </style>

`

This dynamic css looks strangely written...there are no commas in it

**Comment by munirkamal** [comment]
@fatherb,

Cool, you get it fixed. Strange that it worked fine with everywhere we tested on our server, localhost. 

Thank you for confirming the solution worked for you, would be helpful for others. 

@markbiernat this should be working fine for you now as well, I am closing this issue.
