### ISSUE TITLE
History broke in latest Tailor v 1.7.10

### ISSUE THREAD

**Issue by conwaydev** [Enclavely/tailor#131]
Heres a screen recording I made with the twentyseventeen theme with no other plugins: https://cl.ly/0b20181z2f0M, there are no JS errors that happen, but when you try to revert the history it clears out the entire content.

**Comment by munirkamal** [comment]
@conwaydev Thank you for bringing this into our attention. This bug is fixes in the latest version 1.8.0 pushed today.
