### ISSUE TITLE
Notice of undefined index [body_class]

### ISSUE THREAD

**Issue by WPDevHQ** [Enclavely/tailor#134]
With WP_DEBUG set to true I get the following Notice on the Gutenberg edit screen

Notice: Undefined index: body_class in C:\wamp64\www\tailor\wp-content\plugins\tailor\includes\class-tinymce.php on line 92

**Comment by munirkamal** [comment]
Hi @WPDevHQ,

Should be fixed with the latest release, could you please confirm.

Thanks,
Munir

**Comment by WPDevHQ** [comment]
Confirmed as resolved - thank you :)
