### ISSUE TITLE
Encoding troubles

### ISSUE THREAD

**Issue by Arood** [Enclavely/tailor#137]
Hi,

First of all, I'm not 100% percent sure if this is an error caused by Tailor or if something is incorrectly configured on my system since I have a new workstation. However, my issue only happens in Tailor so I'll start here to see if anyone more familiar with the code can help me troubleshoot.

The problem I'm having is that each time I open a page with Tailor, all "special" characters break, like a classic encoding issue. So this text:

`Våra center håller öppet hela dagen och inträdet är gratis för alla deltagare`

becomes this:

`VÃ¥ra centerÂ hÃ¥ller Ã¶ppet hela dagen och intrÃ¤det Ã¤r gratis fÃ¶r alla deltagare.`

This only happens when I open the page in Tailor. Writing these characters and saving works, and opening the page in the WordPress editor works fine.

Can someone help me?

**Comment by munirkamal** [comment]
Hi @Arood,

Thank you to report this, i can confirm it's a bug and we will get it fixed.

Regards,
Munir

**Comment by munirkamal** [comment]
Hi @Arood,

This should be fixed now with the latest release. Please try again and let me know if you still get any errors.

Thanks

**Comment by kkkrist** [comment]
Seems to work for me now. Thanks for the quick fix, much appreciated!
